spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lite_thinking_db?useSSL=false&serverTimezone=UTC
    username: augusto
    password: augusto21
  jpa:
    hibernate:
      ddl-auto: update   # usamos el esquema que ya creaste
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  aws:
    region: us-east-1
    ses:
      from: "augustoecheverriaj@gmail.com"
  s3:
      bucket: "lt-inventarios-demo"   # <-- crea el bucket y pon su nombre aquí
      presign-exp-seconds: 900        # 15 min (ajustable)
  

server:
  port: 8080

app:
  security:
    jwt-secret: "cambia-esta-clave-32+caracteres-al-azar-porfa"
    jwt-expiration-ms: 3600000
  fx:
    base: COP         # moneda base almacenada
    usd: 0.00025      # 1 COP -> USD (≈ 1/4000)
    eur: 0.000232     # 1 COP -> EUR (≈ 1/4300)
  
